//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson2_Cactus.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exibitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exibitions()
        {
            this.Contestant = new HashSet<Contestant>();
            this.Rewarded_Cactuses = new HashSet<Rewarded_Cactuses>();
        }
    
        public int ID_Exibition { get; set; }
        public string Name_Exibition { get; set; }
        public Nullable<System.DateTime> Date_Exibition { get; set; }
        public string Place_Exibition { get; set; }
        public string Rewards_Exibition { get; set; }
        public string Commentaries { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contestant> Contestant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rewarded_Cactuses> Rewarded_Cactuses { get; set; }
    }
}
