//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson2_Cactus.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Of_Matches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public History_Of_Matches()
        {
            this.History_of_rounds = new HashSet<History_of_rounds>();
        }
    
        public int ID_History_of_Match { get; set; }
        public Nullable<int> ID_Match { get; set; }
        public Nullable<int> ID_Client_Contested_History_of_Matches { get; set; }
        public Nullable<double> Total_Win_History_Of_Match { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Matches Matches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_of_rounds> History_of_rounds { get; set; }
    }
}
