//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson2_Cactus.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_of_rounds
    {
        public int ID_history_of_round { get; set; }
        public Nullable<int> ID_round { get; set; }
        public Nullable<double> Bet_round { get; set; }
        public Nullable<double> Coefficent { get; set; }
        public string Exodus_of_round { get; set; }
        public Nullable<double> Reward { get; set; }
        public Nullable<int> ID_history_of_match { get; set; }
    
        public virtual History_Of_Matches History_Of_Matches { get; set; }
        public virtual rounds rounds { get; set; }
    }
}
