//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson2_Cactus.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rewarded_Cactuses
    {
        public int ID_RewardCactuses { get; set; }
        public Nullable<int> ID_Cactus { get; set; }
        public Nullable<int> ID_Exibition { get; set; }
    
        public virtual Cactus Cactus { get; set; }
        public virtual Exibitions Exibitions { get; set; }
    }
}
