//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson2_Cactus.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class rounds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rounds()
        {
            this.History_of_rounds = new HashSet<History_of_rounds>();
        }
    
        public int ID_round { get; set; }
        public Nullable<int> ID_match { get; set; }
        public Nullable<double> Bet_rounds { get; set; }
        public Nullable<double> Coefficent { get; set; }
        public string Exodus_of_round { get; set; }
        public Nullable<double> Reward { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_of_rounds> History_of_rounds { get; set; }
        public virtual Matches Matches { get; set; }
    }
}
